services:
  # The name of our service is "database"
  # but you can use the name of your choice.
  # Note: This may change the commands you are going to use a little bit.
  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASECONNECTION__USERNAME} 
      POSTGRES_PASSWORD: ${DATABASECONNECTION__PASSWORD}
      POSTGRES_DB: ${DATABASECONNECTION__DATABASE}
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/